database:
    url: "postgres://user:password@localhost/db"
    max_connections: 10
    min_connections: 1
    connect_timeout: 30
    idle_timeout: 600
server:
    host: "127.0.0.1"
    port: 10001
jwt:
    secret: "your-jwt-secret-key"
    issuer: "alion-admin"
    access_token_expire: 3600  # 1 hour in seconds
    refresh_token_expire: 604800  # 7 days in seconds
    audience: "alion-admin-client"
