database:
    url: "postgres://postgres:postgres@localhost:5432/alion-admin"
    max_connections: 10
    min_connections: 1
    connect_timeout: 30
    idle_timeout: 600
server:
    host: "0.0.0.0"
    port: 9528
jwt:
    jwt_secret: "alion-admin"
    issuer: "https://github.com/ByteByteBrew/alion-admin"
    expire: 7200
redis:
    mode: single
    url: "redis://password@127.0.0.1:6379/0"
# 由于本项目最终目标可能仅仅作为一般rbac项目,因此redis作为可选组件,可以根据实际情况进行按需使用
# 有需求自行取消注释
# redis:
#     mode: cluster
#     urls:
#         - "redis://alion:123456@127.0.0.1:7001"
#         - "redis://alion:123456@127.0.0.1:7002"
#         - "redis://alion:123456@127.0.0.1:7003"
#         - "redis://alion:123456@127.0.0.1:7004"
#         - "redis://alion:123456@127.0.0.1:7005"
#         - "redis://alion:123456@127.0.0.1:7006"
# redis_instances:
#     - name: "cache"
#       redis:
#           mode: single
#           url: "redis://:123456@localhost:6379/11"
#     - name: "test"
#       redis:
#           mode: single
#           url: "redis://:123456@localhost:6379/12"
