# 数据库配置
# url: 数据库连接字符串，格式为 postgres://用户名:密码@主机:端口/数据库名
# max_connections: 最大连接数
# min_idle: 最小空闲连接数
# connect_timeout: 连接超时时间（秒）
# idle_timeout: 空闲连接超时时间（秒）
# max_lifetime: 连接最大生命周期（秒）
database:
    url: "postgres://alion:alion%40123.@pgbouncer:6432/alion-admin"
    max_connections: 5
    min_idle: 1
    connect_timeout: 5
    idle_timeout: 60
    max_lifetime: 3600

# 服务配置
# host: 监听地址
# port: 监听端口
server:
    host: "0.0.0.0"
    port: 10001

# JWT 配置
# secret: JWT密钥
# access_token_expire: 访问令牌过期时间（秒）
# refresh_token_expire: 刷新令牌过期时间（秒）
# issuer: 签发者
# audience: 受众
jwt:
    secret: "alion-admin"
    access_token_expire: 7200
    refresh_token_expire: 604800
    issuer: "git@github.com:ya-team/alion-admin-api.git"
    audience: "alion-admin"

# Redis 配置
# mode: 连接模式（single 单机，cluster 集群）
# url: 单机模式下的Redis连接地址
redis:
    mode: single
    url: "redis://:123456@redis:6379/10"

# 可选组件配置，按需取消注释
# mongo:
#     uri: "mongodb://localhost:27017"  # MongoDB连接地址
# s3:
#     region: "oss-cn-beijing"          # S3存储区域
#     access_key_id: "x"                # S3访问密钥ID
#     secret_access_key: "x"            # S3访问密钥Secret
#     endpoint: "https://oss-cn-beijing.aliyuncs.com"  # S3服务端点
