# ======================================
# Core Build Configuration
# ======================================
[build]
jobs = 16
pipelining = true
incremental = false

[rust]
channel = "stable"
debuginfo = 0
parallel-compiler = true
deny-warnings = true

# ======================================
# Development Profile
# ======================================
[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256
rpath = false

# ======================================
# Release Profile
# ======================================
[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1
rpath = false
strip = true
split-debuginfo = "off"

# ======================================
# Universal Optimizations
# ======================================
[target.'cfg(all())']
rustflags = [
    "-C", "target-cpu=native",
    "-C", "force-frame-pointers=no",
    "-C", "link-arg=-s",
    "-C", "prefer-dynamic=no",
    "-D", "warnings"
]

# ======================================
# Release Mode Optimizations
# ======================================
[target.'cfg(not(debug_assertions))']
rustflags = [
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
    "-C", "embed-bitcode=yes",
    "-C", "target-feature=+crt-static"
]

# ======================================
# Architecture Optimizations (Release Only)
# ======================================
[target.'cfg(all(target_arch = "x86_64", not(debug_assertions)))']
rustflags = [
    "-C", "target-feature=+sse3,+ssse3,+sse4.1,+sse4.2,+avx,+avx2,+fma,+f16c,+popcnt,+fxsr,+bmi1,+bmi2,+lzcnt,+movbe"
]

[target.'cfg(all(target_arch = "aarch64", not(debug_assertions)))']
rustflags = [
    "-C", "target-feature=+neon,+fp-armv8,+crypto,+aes,+sha2,+crc,+lse,+rdm,+rcpc,+dotprod"
]

[target.'cfg(all(target_arch = "aarch64", target_os = "macos", not(debug_assertions)))']
rustflags = [
    "-C", "target-feature=+neon,+fp-armv8,+crypto,+aes,+sha2,+crc,+lse,+rdm,+rcpc,+dotprod,+fp16,+i8mm"
]

# ======================================
# Package Optimizations
# ======================================
[profile.release.package."*"]
opt-level = 3
codegen-units = 1
incremental = false

# ======================================
# Documentation
# ======================================
[doc]
browser = "firefox"
opts = ["--enable-index-page", "--enable-search", "--document-private-items"]
