//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "casbin_rule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub ptype: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub v0: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub v1: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub v2: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub v3: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub v4: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub v5: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
