//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub mod prelude;

pub mod casbin_rule;
pub mod sea_orm_active_enums;
pub mod sys_access_key;
pub mod sys_domain;
pub mod sys_endpoint;
pub mod sys_login_log;
pub mod sys_menu;
pub mod sys_operation_log;
pub mod sys_organization;
pub mod sys_role;
pub mod sys_role_menu;
pub mod sys_tokens;
pub mod sys_user;
pub mod sys_user_role;
