//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::{
    casbin_rule::Entity as CasbinRule, sys_access_key::Entity as SysAccessKey,
    sys_domain::Entity as SysDomain, sys_endpoint::Entity as SysEndpoint,
    sys_login_log::Entity as SysLoginLog, sys_menu::Entity as SysMenu,
    sys_operation_log::Entity as SysOperationLog, sys_organization::Entity as SysOrganization,
    sys_role::Entity as SysRole, sys_role_menu::Entity as SysRoleMenu,
    sys_tokens::Entity as SysTokens, sys_user::Entity as SysUser,
    sys_user_role::Entity as SysUserRole,
};
